repository:
  name: 'express-hexagonal-architecture'
  description: 'Express Hexagonal Architecture'
  homepage: 'https://github.com/parraletz/express-hexagonal-architecture'
  topics:
    - 'express'
    - 'hexagonal-architecture'
    - 'typescript'
    - 'nodejs'
    - 'docker'
    - 'kubernetes'
  owner: 'parraletz'
  has_wiki: false
  private: false
  has_issues: true
  has_projects: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  branches:
    - name: main
      protection:
        required_pull_request_reviews:
          required_approving_review_count: 1
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions: null
